language: perl
perl:
  - "5.22"
  - "5.24"
before_install:
  - "cp -v mirrorpad.yml.smp mirrorpad.yml"
  - sudo ./build.sh
notifications:
  irc:
    channels:
      - "chat.freenode.net#pressecitron"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url} Build details : %{build_url}"
      - "%{commit_message}"
    use_notice: true
script:
  - t/alltests

