language: perl
perl:
  - "5.20"
notifications:
  irc:
    channels:
      - "chat.freenode.net#pressecitron"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url} Build details : %{build_url}"
      - "%{commit_message}"
    use_notice: true
install:
  - sudo ./build.sh
script:
  - t/alltests

