language: perl
perl:
  - "5.22"
  - "5.24"
before_install:
  - "cp -v mirrorpad.yml.smp mirrorpad.yml"
  - sudo apt-get -qq update
  - sudo apt-get instal -y libconfig-yaml-perl libwww-perl liblwp-protocol-https-perl libencode-perl liburi-encode-perl
notifications:
  irc: "chat.freenode.net#pressecitron"
script:
  - cd t && ./01_mirrorpad

