language: perl
perl:
  - "5.22"
  - "5.24"
before_install:
  - "cp -v mirrorpad.yml.smp mirrorpad.yml"
  - sudo apt-get -qq update
  - sudo apt-get install -y libconfig-yaml-perl libwww-perl liblwp-protocol-https-perl libencode-perl liburi-encode-perl
notifications:
  irc: "chat.freenode.net#pressecitron"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url} Build details : %{build_url}"
      - "%{commit_message}"
    use_notice: true
script:
  - cd t && ./01_mirrorpad

