language: perl
perl:
  - "5.20"
notifications:
  irc:
    channels:
      - "chat.freenode.net#pressecitron"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url} Build details : %{build_url}"
      - "%{commit_message}"
    use_notice: true
install:
  - cp -v mirrorpad.yml.smp mirrorpad.yml
  - cpanm --notest Config::YAML Encode URI::Encode LWP::UserAgent LWP::Protocol::https Etherpad
script:
  - t/alltests

