#!/bin/bash

printf "$PRINTFPATTERN" $0 : "Test de lancement sans fichier de config"

# Si un fichier de config existe on le renomme
if test -r "mirrorpad.yml";
then
  mv mirrorpad.yml mirrorpad.yml.$$
fi

OUTPUT=$(./mirrorpad 2>&1 >/dev/null)
RC=$?
echo -n "RC=$RC "

if test "$RC" -eq "5";
then
  # Test reussi
  echo "[  OK  ]"
  RC=0
else
  echo "[FAILED]"
  RC=1
fi

echo "$OUTPUT"

# On remet le fichier qui existait
if test -r "mirrorpad.yml.$$";
then
  mv mirrorpad.yml.$$ mirrorpad.yml
fi

exit "$RC"

