#!/bin/bash

printf "$PRINTFPATTERN" $0 : "URL Simple, privée, bien formée, sans accent, avec export/txt."

if test "$TRAVIS" == "true";
then
  echo "[ SKIP ]"
  exit 0
fi

URL=https%3A%2F%2Fpad.exegetes.eu.org%2Fgroup.html%2F19%2Fpad.html%2Fg.STVKtWnA83RsmVUC%24Abro2-PRIVE%2Fexport%2Ftxt

OUTPUT=$(./mirrorpad "$URL" 2>&1 >/dev/null)
RC=$?
echo -n "RC=$RC "
if test "$RC" -ne "0";
then
  # Test raté
  echo "[FAILED]"
else
  echo "[  OK  ]"
fi
echo "$OUTPUT"
exit "$RC"

