#!/bin/bash

printf "$PRINTFPATTERN" $0 : "URL Simple, privée, bien formée, sans accent."

if test "$TRAVIS" == "true";
then
  echo "[ SKIP ]"
  exit 0
fi

URL=$(tail -n1 url_test.priv.txt)

OUTPUT=$(./mirrorpad "$URL" 2>&1 >/dev/null)
RC=$?
echo -n "RC=$RC "
if test "$RC" -ne "0";
then
  # Test raté
  echo "RC=$RC [FAILED]"
else
  echo "RC=$RC [  OK  ]"
fi
echo "$OUTPUT"
exit "$RC"

