#!/bin/bash
MAXRC=0
export PRINTFPATTERN='%-31s %s %-70s'
for test in t/*;
do
  if test -x "$test" -a "$test" != "$0";
  then
    $test
    RC=$?
    printf "RC:=(%d) (%s)\n\n" $RC $test
    if test "$RC" -ne "0";
    then
      MAXRC="$RC"
    fi
  fi
done

exit $MAXRC
